apiVersion: v1
kind: Service
metadata:
  name: svc-portal-noticias
spec:
  type: NodePort
  ports:
    - port: 80
      #targetPort: 80
      # O node port deve ser entre 30000 e 32767
      nodePort: 30000
  selector:
    app: portal-noticias