apiVersion: v1
kind: Service
metadata:
  name: svc-sistema-noticias
spec:
  type: NodePort
  ports:
    - port: 80
      #targetPort: 80
      # O node port deve ser entre 30000 e 32767 (lembrando que a porta 30000 já esta em uso em outro serviço)
      nodePort: 30001
  selector:
    app: sistema-noticias